export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REPONSE_IS_PENDING = 'REPONSE_IS_PENDING';
export const REPONSE_IS_SUCCESS = 'REPONSE_IS_SUCCESS';
export const REPONSE_IS_FAILED = 'REPONSE_IS_FAILED';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';